export const STR = {
  metaTitle: "Astral Reverie — a consequence-free gacha simulator",
  sharedMetaTitle: "Shared pull — Astral Reverie",
  appName: "ASTRAL REVERIE",
  appKicker: "Consequence-free summoning",
  primaryNav: "Simulator views",
  navBanner: "Signal",
  navAlbum: "Archive",
  navStats: "Audit",
  navLog: "Receipts",
  muteOn: "Mute sound",
  muteOff: "Enable sound",
  shareFacebook: "Share",
  shareFacebookAria: "Share Astral Reverie to Facebook",
  shareResult: "Share to Facebook",
  shareCard: "Share card",
  sharePull: count => `Share ×${count} pull`,
  sharePopupBlocked: "Facebook share was blocked. Allow popups and try again.",
  closeLabel: "Close",
  limitedBadge: "Limited signal · live",
  eventKicker: "Celestial transmission 01",
  bannerTitle: "Duskfall Requiem",
  bannerSubtitle: "Seren · the Dusk Warden",
  eventEnds: "Signal collapses in 27d 11h",
  featuredOdds: "Featured UR 50%",
  pullKicker: "Awaiting instruction",
  pullTitle: "Open the signal",
  urPity: "UR resonance",
  baseRate: "Base rate",
  softPity: "Soft pity",
  hardPity: "Hard pity",
  pullOne: "Trace ×1",
  pullTen: "Trace ×10",
  pullTenCost: "1,600 · SR+ guaranteed",
  autoOpenTen: "Auto-open ×10",
  autoOpenHint: "hands-free card reveal",
  fakeSpendLabel: "Imaginary spend",
  fakeSpendSuffix: "still in your bank",
  keySingle: "single",
  keyMulti: "multi",
  keySkip: "skip / close",
  keyDigitOne: "1",
  keySpace: "Space",
  keyEscape: "Esc",
  archiveKicker: "Recovered signatures",
  albumTitle: "Astral archive",
  auditKicker: "Statistical autopsy",
  statsTitle: "Your luck, audited",
  statsIntro: "No mysticism. Just variance with excellent lighting.",
  verdictLabel: "Official verdict",
  resetLabel: "Erase the evidence",
  resetConfirm: "Press again to erase everything",
  logKicker: "Session ledger",
  logTitle: "The receipts",
  logIntro: "Latest results first. The void keeps immaculate books.",
  footerNotice: "A satire with fake currency. No purchases, no account, no value.",
  creditLine: "Made with love by Agent Dev Thai",
  storeKicker: "Definitely not a shop",
  topupTitle: "Stellar shards",
  topupIntro: "Every package is instant, free, and still somehow manipulative.",
  lifetimeSpend: "Would-be lifetime spend",
  skipLabel: "Skip  »",
  tapContinue: "tap, press Space, or use gamepad A",
  revealAll: "Reveal all  »",
  summaryKicker: "Transmission complete",
  sharedSummaryKicker: "Shared transmission",
  summaryTitle: "Signal results",
  collectLabel: "Collect",
  enterSimulatorLabel: "Enter simulator",
  againLabel: "Again ×10 · 1,600",
  newBadge: "NEW",
  ownedBadge: count => `×${count}`,
  pullNumber: number => `#${number}`,
  pityHint: (pity, hard) => pity >= Math.floor(hard * 0.8)
    ? "Soft pity is active. The signal knows you can feel it."
    : `${hard - pity} traces until the guarantee.`,
  albumProgress: (owned, total) => `${owned} / ${total} recovered`,
  archiveTeaserKicker: "Next transmission",
  archiveTeaserTitle: "Coming soon",
  archiveTeaserCopy: "More signatures are gathering beyond the gate.",
  archiveCompleteKicker: "Archive anomaly",
  archiveCompleteTitle: "You found the edge",
  archiveCompleteCopy: "Every known signal recovered. The next one is hiding from you.",
  logEmpty: "No traces yet. Your imaginary wallet is safe. For now.",
  collectionEmpty: "Unknown signature",
  seededLabel: seed => `Signal seed ${seed}`,
  sharedFooterLabel: "Shared result · local progress unchanged",
  insufficient: "Not enough shards. The fake shop has fake solutions.",
  topupToast: (gems, price) => `+${gems.toLocaleString()} shards · $${price} of imaginary money`,
  resetToast: "Evidence erased. Pattern-seeking intact.",
  totalTraces: "Total traces",
  sessionTraces: count => `${count} this session`,
  urRecovered: "UR recovered",
  ssrRecovered: count => `${count} SSR recovered`,
  urRate: "Your UR rate",
  expectedRate: "0.6% expected",
  wouldSpend: "Would-be spend",
  burritosSaved: count => `≈ ${count} burritos saved`,
  verdictEmpty: "Run a trace first. The audit needs data; the void needs feeding.",
  verdictHot: "You are running hot. This is the exact moment a real game would encourage you to mistake variance for destiny.",
  verdictAverage: "Perfectly average luck. The system neither loves nor hates you; it merely has another animation queued.",
  verdictZero: "Zero URs. Pity was designed for this exact emotional weather. At least this version cannot invoice you.",
  verdictCold: "Below rate. In a real game this is where friction disappears from the purchase flow. Here, you get a sentence instead.",
  buildNormal: "Crossing the eclipse gate",
  buildNearMiss: "The signal is turning gold—",
  genericCharacterAlt: name => `Card artwork for ${name}`,
  packageButton: (gems, price) => `${gems.toLocaleString()} shards, simulated price $${price}`,
};

export const PULL_FEEDBACK = {
  C: {
    build: "Salvage hatch attempting dignity",
    verdict: "Salvage-grade signal",
    summary: "The void sent office supplies. Generous, in its own way.",
  },
  R: {
    build: "Cobalt scan stabilized",
    verdict: "Stable signal",
    summary: "Blue light: respectable, punctual, and nobody's screenshot.",
  },
  SR: {
    build: "Harmonic resonance climbing",
    verdict: "Resonant signal",
    summary: "Purple—the system's most efficient compromise between hope and restraint.",
  },
  SSR: {
    build: "Solar gate breached",
    verdict: "Radiant signal",
    summary: "Okay, that one was actually good. Suspicious, but good.",
  },
  UR: {
    build: "Impossible signature detected",
    verdict: "Impossible signal",
    summary: "Jackpot. Screenshot it before probability remembers itself.",
  },
};

export const RARITY = {
  C: { label: "C · Common", stars: "✦", tone: "common" },
  R: { label: "R · Rare", stars: "✦ ✦", tone: "rare" },
  SR: { label: "SR · Resonant", stars: "✦ ✦ ✦", tone: "sr" },
  SSR: { label: "SSR · Radiant", stars: "✦ ✦ ✦ ✦", tone: "ssr" },
  UR: { label: "UR · Limited", stars: "✦ ✦ ✦ ✦ ✦", tone: "ur" },
};

const item = (id, name, title, rarity, sigil, art = "", artMode = "contain") => ({
  id,
  name,
  title,
  rarity,
  sigil,
  art,
  artMode,
});

export const ITEMS = [
  item("seren", "Seren", "the Dusk Warden", "UR", "☾", "./assets/generated/card-art/seren.webp", "cover"),
  item("kaelis", "Kaelis", "Star Devourer", "UR", "◒", "./assets/generated/card-art/kaelis.webp", "cover"),
  item("nyx", "Nyx", "Terminal Dawn", "UR", "⌁", "./assets/generated/card-art/nyx.webp", "cover"),
  item("aurelia", "Aurelia", "Gilded Oracle", "SSR", "◎", "./assets/generated/card-art/aurelia.webp", "cover"),
  item("vance", "Vance", "Debt Collector", "SSR", "◇", "./assets/generated/card-art/vance.webp", "cover"),
  item("miko", "Miko", "Shrine of Static", "SSR", "⌇", "./assets/generated/card-art/miko.webp", "cover"),
  item("thorne", "Thorne", "Iron Requiem", "SSR", "†", "./assets/generated/card-art/thorne.webp", "cover"),
  item("ilsa", "Ilsa", "Frostbound Teller", "SSR", "❄", "./assets/generated/card-art/ilsa.webp", "cover"),
  item("rho", "Rho", "Equation Zero", "SSR", "∅", "./assets/generated/card-art/rho.webp", "cover"),
  item("bram", "Bram", "Cinder Sentinel", "SR", "△", "./assets/generated/card-art/bram.webp", "cover"),
  item("cyra", "Cyra", "Echo Diver", "SR", "≋", "./assets/generated/card-art/cyra.webp", "cover"),
  item("dov", "Dov", "Quiet Cartographer", "SR", "⌖", "./assets/generated/card-art/dov.webp", "cover"),
  item("ember", "Ember", "Match-Girl Major", "SR", "✢", "./assets/generated/card-art/ember.webp", "cover"),
  item("fenn", "Fenn", "Tidewalker", "SR", "≈", "./assets/generated/card-art/fenn.webp", "cover"),
  item("gale", "Gale", "Stormstitcher", "SR", "ϟ", "./assets/generated/card-art/gale.webp", "cover"),
  item("hana", "Hana", "Petal Vanguard", "SR", "❋", "./assets/generated/card-art/hana.webp", "cover"),
  item("charm", "Voidglass Charm", "Trinket", "R", "◈", "./assets/generated/card-art/charm.webp", "cover"),
  item("lens", "Cracked Star Lens", "Trinket", "R", "◉", "./assets/generated/card-art/lens.webp", "cover"),
  item("coil", "Humming Coil", "Trinket", "R", "@", "./assets/generated/card-art/coil.webp", "cover"),
  item("map", "Half a Star Map", "Trinket", "R", "⌁", "./assets/generated/card-art/map.webp", "cover"),
  item("key", "Key to Nowhere", "Trinket", "R", "⚿", "./assets/generated/card-art/key.webp", "cover"),
  item("vial", "Vial of Almost", "Trinket", "R", "⌑", "./assets/generated/card-art/vial.webp", "cover"),
  item("quill", "Comet Quill", "Trinket", "R", "〆", "./assets/generated/card-art/quill.webp", "cover"),
  item("bell", "Silent Bell", "Trinket", "R", "◡", "./assets/generated/card-art/bell.webp", "cover"),
  item("cog", "Cracked Cog", "Junk", "C", "⚙", "./assets/generated/card-art/cog.webp", "cover"),
  item("canteen", "Dented Canteen", "Junk", "C", "▱", "./assets/generated/card-art/canteen.webp", "cover"),
  item("rock", "Suspicious Rock", "Junk", "C", "⬟", "./assets/generated/card-art/rock.webp", "cover"),
  item("coupon", "Expired Coupon", "Junk", "C", "%", "./assets/generated/card-art/coupon.webp", "cover"),
  item("sock", "Cosmic Sock (one)", "Junk", "C", "∿", "./assets/generated/card-art/sock.webp", "cover"),
  item("manual", "Unread Manual", "Junk", "C", "≣", "./assets/generated/card-art/manual.webp", "cover"),
  item("battery", "Dead Battery", "Junk", "C", "▭", "./assets/generated/card-art/battery.webp", "cover"),
  item("receipt", "Trace Receipt", "Junk", "C", "§", "./assets/generated/card-art/receipt.webp", "cover"),
];

export const SNARK = [
  "The next one is definitely the UR. Definitely.",
  "You are three traces from happiness. Always three.",
  "Statistically, someone just got Seren. Not you, but someone.",
  "Pity is not a strategy. It is, however, your strategy.",
  "This signal ends soon. So does your restraint.",
  "It is only gambling if the currency can leave this browser.",
  "Your UR is waiting. It has been ‘waiting’ for sixty traces.",
  "One more multi. As a controlled experiment.",
];

export const SUMMARY_SNARK = [
  "A perfectly average outcome. The most psychologically efficient kind.",
  "The house always wins. Good thing there is no house.",
  "That violet flash felt persuasive though, right?",
  "Imagine if these were real. Now imagine the invoice.",
  "You will remember the UR and forget the two hundred traces before it.",
];

export const PACKAGES = [
  { gems: 1600, price: "0.99", note: "One more universe" },
  { gems: 8000, price: "14.99", note: "Pity speedrun" },
  { gems: 32000, price: "49.99", note: "Weekend successfully erased" },
  { gems: 80000, price: "99.99", note: "The full fever dream" },
];
